### ISSUE TITLE
A Typo

### ISSUE THREAD

**Issue by thuongxanh8** [SethClydesdale/tobira-study-resources#12]
https://sethclydesdale.github.io/tobira-study-resources/lessons/lesson-1/kanji-review-wb-14/

第1課 - 復習漢字の練習：問題14
11. **ゆうそく**をたべてから．．．
ゆうそく⋙ ゆうしょく

**Comment by SethClydesdale** [comment]
Hello @thuongxanh8, thank you for reporting this typo; it should be fixed now!
