### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by esposim** [SethClydesdale/tobira-study-resources#14]
Hi, i'd like to report a spelling mistake on tobira's grammar on your site.
link: https://sethclydesdale.github.io/tobira-study-resources/lessons/appendix/grammar-index/#l3-p9
mistake: 技術が発達したために、生活がとても便利いなってきた
error: 便利い
 correction: 便利に

that's it. thank you very much for your site, it's so helpful :) , i'm glad to help.

**Comment by SethClydesdale** [comment]
Hello @esposim!

Thank you again for reporting this typo; it should be corrected now!
