### ISSUE TITLE
Incorrect Parsing Lesson 10

### ISSUE THREAD

**Issue by hubertogitero** [SethClydesdale/tobira-study-resources#19]
In 第10課 - 単語：読み物・その1 there's a parsing error for two entries in the "Spelling Practice" and "Write the Definition" exercise types. 
Specifically for: 
- one after another 次々(とに/)
- to serve (food/drink) (飲み物食べ物を/)出す

I assume it has to do with the "/" being in the wrong place but I am not very knowledgeable on these issues.
Thank you for making this website!

**Comment by SethClydesdale** [comment]
Hello @hubertogitero!

Thank you for reporting this! It certainly appears to be a bug with the auto-parser for vocab entries that contain parentheses. I'll look into fixing this.

**Comment by SethClydesdale** [comment]
Spelling Practice is a little finnicky still, but the Write the Definition variation of this exercise should be fixed.
