### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by Andres-Salamanca** [SethClydesdale/tobira-study-resources#2]
link: https://sethclydesdale.github.io/tobira-study-resources/lessons/lesson-2/grammar-wb-7/
( ) 日本は南北に長いために、南と北でが気候が大きく違う。X
( ) 日本は南北に長いために、南と北で**は**気候が大きく違う。○

**Comment by Andres-Salamanca** [comment]
link: https://sethclydesdale.github.io/tobira-study-resources/lessons/lesson-2/grammar-wb-8/
in the secondary answer of question c.1
あめがふってしまったために、きのうのまつり**り**にあまりひとがこなくてざんねんだった X
あめがふってしまったために、きのうのまつりにあまりひとがこなくてざんねんだった ○

**Comment by SethClydesdale** [comment]
Hello @Andres-Salamanca, thank you for reporting these! I'll have them corrected a little later today 👍

**Comment by SethClydesdale** [comment]
Sorry, forgot to let you know yesterday, but these typos should be corrected now! If you run into any other problems, typos, etc., please feel free to open a new issue to let me know.
