### ISSUE TITLE
Minor review bug

### ISSUE THREAD

**Issue by hubertogitero** [SethClydesdale/tobira-study-resources#21]
In a few of the "Write the Definition" vocab exercises answers will be graded as "correct" if you enter nothing:

第1課 - 単語：会話文・その1:
12. to be included; come in; get in; join

第2課 - 単語：読み物・その3:
21. like written/spoken language

第5課 - 単語：会話文:
13. to be put (on top of something)

第6課 - 単語：読み物1・その1:
6. please

There may be more of these, but these are the only ones I found.

**Comment by SethClydesdale** [comment]
Hello @hubertogitero, thank you for reporting this!

I took a quick look and it appears there was an issue with the answer checker that should be resolved now. If you notice any other issues, feel free to let me know!

**Comment by hubertogitero** [comment]
Thank you once more for making this website!
