### ISSUE TITLE
Katakana not accepted

### ISSUE THREAD

**Issue by RuntimeX** [SethClydesdale/tobira-study-resources#9]
Answers using katakana for names is marked incorrect when the katakana matches its hiragana counterpart, while kanji is accepted as correct for answers that would be hiragana or katakana.

**Comment by SethClydesdale** [comment]
Hello, sorry for the late reply!

For native names used on the site, hiragana and kanji are used. I could add some alternatives for some, however. Would you happen to have a link to the problems in question?
